name: phbenchmark
channels:
  - conda-forge
dependencies:
  - python==3.11
  - time
  - pip
  - pip:
      - ripser==0.6.12
      - cripser==0.0.21
      - gudhi==3.11.0
      - -e ./PixHomology
      - -e .
