[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phbenchmark"
version = "0.1.0"
description = "Persistent Homology Benchmark for 2D data."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
  { name = "Riccardo Ceccaroni", email = "riccardo.ceccaroni.95@gmail.com" }
]
dependencies = [
  "typer",
  "h5py",
  "gdown",
  "tqdm",
  "pandas",
  "jinja2",
]

[tool.setuptools.packages.find]
include = ["phbenchmark*"]

[project.scripts]
phbenchmark = "phbenchmark.app:app"
